export const LOGIN_SUCCESS = "LOGINLOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGOUT = "LOGOUT";

export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_QESTIONS = "FETCH_QESTIONS";
export const FETCH_QUIZZES = "FETCH_QUIZZES";

export const SET_SELECTED_ANSWER = "SET_SELECTED_ANSWER";
export const CATEGORY = "CATEGORY";
export const DIFFICULTY = "DIFFICULTY";
export const SCORE = "SCORE";
